### ISSUE TITLE
microservice oidc fails to start after a new install

### ISSUE THREAD

**Issue by chevalleyc** [QEWD-Courier/Arc-QEWD-Courier-hive#19]
Following the readme to install QEWD, oidc fails with unresolved config:

```
$ docker logs -f oidc

.....

========================================================
QEWD.js is listening on port 8080
========================================================
Wait a couple of seconds for oidc-provider to be available
internal/modules/cjs/loader.js:582
    throw err;
    ^

Error: Cannot find module '/opt/qewd/node_modules/oidc-provider'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
    at Function.Module._load (internal/modules/cjs/loader.js:506:25)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/opt/qewd/mapped/modules/qewd-openid-connect/lib/loader.js:31:18)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! qewd-server@2.40.0 start: `NODE_PATH=/opt/qewd/mapped/modules node qewd.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the qewd-server@2.40.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-11-13T02_56_42_415Z-debug.log
```
There is no /opt/qewd directory following the installation. (installed on CentOS 7). Further, log /root/.npm/_logs/2018-11-13T02_56_42_415Z-debug.log is not created.

NB. Seems that:
```
openid-connect-server/modules/qewd-openid-connect/lib/loader.js:const Provider = require('/opt/qewd/node_modules/oidc-provider');
``` 

is hardcoded.

this is also an issue in the startup script as:

```
$ sudo docker run -d --rm --name oidc -p 8080:8080 -v ~/helm/openid-connect-server:/opt/qewd/mapped -v ~/helm/openid-connect-server/www:/opt/qewd/www -v ~/helm/settings:/opt/qewd/mapped/settings -v ~/helm/yottadb/openid-connect-server:/root/.yottadb/r1.22_x86_64/g rtweed/qewd-server
```

**Comment by PhilBarrett** [comment]
New version now in place, so this should be resolved.
